name: cloud_firestore_example
description: Demonstrates how to use the firestore plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  cloud_firestore: any
  firebase_core: any
  flutter:
    sdk: flutter


dev_dependencies:
  drive: ^0.1.0
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
